//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterDetail
    {
        public int EmpID { get; set; }
        public byte RType { get; set; }
        public Nullable<bool> Repeat { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual RosterType RosterType { get; set; }
    }
}
