//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLeaveQuota
    {
        public int EmpID { get; set; }
        public string EmpLvType { get; set; }
        public string LeaveType { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<double> JanConsumed { get; set; }
        public Nullable<double> FebConsumed { get; set; }
        public Nullable<double> MarchConsumed { get; set; }
        public Nullable<double> AprConsumed { get; set; }
        public Nullable<double> MayConsumed { get; set; }
        public Nullable<double> JuneConsumed { get; set; }
        public Nullable<double> JulyConsumed { get; set; }
        public Nullable<double> AugustConsumed { get; set; }
        public Nullable<double> OctConsumed { get; set; }
        public Nullable<double> SepConsumed { get; set; }
        public Nullable<double> NovConsumed { get; set; }
        public Nullable<double> DecConsumed { get; set; }
        public Nullable<double> TotalForYear { get; set; }
        public Nullable<double> YearRemaining { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> GrandTotalRemaining { get; set; }
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string SiteName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Remarks { get; set; }
        public string SectionName { get; set; }
        public string DeptName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> Expr1 { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> DivisionID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> SectionID { get; set; }
        public Nullable<short> DeptID { get; set; }
        public Nullable<byte> GradeID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<short> LocID { get; set; }
    }
}
