//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmergencyDetail
    {
        public string DesignationName { get; set; }
        public string DeptName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string EmpName { get; set; }
        public string EmpNo { get; set; }
        public string SectionName { get; set; }
        public string EmgNo { get; set; }
        public string EmgName { get; set; }
    }
}
